name: brats23_sagittal_fold1_SS2D_nopooling
data_root: /gpfs/scratch1/shared/apiaghiardelli/BRATS2023_preprocessed/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData
val_fold: 1
view: sagittal
model: orig
# model architecture
patch_size: 2
linear_projection: true
residual_connections: true
dwconv2d_spiking: true
patch_embedding_spiking: true
# training
# Set this to an existing run directory to resume from checkpoint_last.pt.
resume_from: null
batch_size_subjects: 8
lr: 0.001
epochs: 120
weight_decay: 0.00001
grad_clip: 0.3
tbptt_k: 1
alpha_fptt: 0.1
beta_fptt: 0.15
rho_fptt: 0.0
lambda_fptt: 1.5
lambda_bce: 0.5
lambda_dice: 0.5
eval_every: 1
eval_batch_slices: 16
prob_threshold: 0.5
subjects_per_fold: null  # null/commented = use all subjects; otherwise first n per train/val fold
# overfit_subjects: 5
